[theme]
# Hot Barbie-pink accent
primaryColor = "#FB81CD"

# Light pastel background (not plain white, a soft pink wash)
backgroundColor = "#FFF4FA"

# Sidebar / widgets (slightly brighter pastel for contrast)
secondaryBackgroundColor = "#FFE6F3"

# Text color (dark, but not harsh black — smooth charcoal gray)
textColor = "#2B2B2B"

# Fun but professional font
font = "sans serif"
